### Create advert
POST http://127.0.0.1:8000/api/adverts/
Content-Type: application/json

{
  "title": "Test Title",
  "description": "Test Description",
  "owner": "Test User",
  "owner_email": "alzex@gmail.com"
}

### Update advert
PATCH http://127.0.0.1:8000/api/adverts/2/
Content-Type: application/json

{
  "title": "Test Title",
  "description": "Update Description",
  "owner": "Test Users"
}

### Get all adverts
GET http://127.0.0.1:8000/api/adverts/
Accept: application/json

### Get advert with id
GET http://127.0.0.1:8000/api/adverts/2/
Accept: application/json

### Delete advert
DELETE http://127.0.0.1:8000/api/adverts/2/
Accept: application/json

### Send emails
POST http://127.0.0.1:8000/tasks/
Content-Type: application/json

{
  "subject": "Test Email",
  "msg": "This is my test email!"
}

### Send emails status
GET http://127.0.0.1:8000/tasks/709f2bb0-5803-49ef-92ba-9b96455a674e/
Content-Type: application/json
